/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author USUARIO
 */
public class Loggin2 extends javax.swing.JFrame {

    /**
     * Creates new form Loggin2
     */
    public Loggin2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PagPrinLoggin = new javax.swing.JPanel();
        Usuario = new javax.swing.JLabel();
        CamUsuario = new javax.swing.JTextField();
        Contrasena = new javax.swing.JLabel();
        CContrasena = new javax.swing.JTextField();
        OlvidoContrasena = new javax.swing.JLabel();
        ImagenUsuario = new javax.swing.JLabel();
        BotonIngreso = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PagPrinLoggin.setBackground(new java.awt.Color(255, 153, 255));
        PagPrinLoggin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Usuario.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        Usuario.setText("Usuario");
        PagPrinLoggin.add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));
        PagPrinLoggin.add(CamUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 230, -1));

        Contrasena.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        Contrasena.setText("Contraseña");
        PagPrinLoggin.add(Contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));
        PagPrinLoggin.add(CContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 230, -1));

        OlvidoContrasena.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        OlvidoContrasena.setText("Olvido su contraseña?");
        PagPrinLoggin.add(OlvidoContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 150, -1));

        ImagenUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono usuario.png"))); // NOI18N
        ImagenUsuario.setText("jLabel2");
        PagPrinLoggin.add(ImagenUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 120, 130));

        BotonIngreso.setText("Ingresar");
        BotonIngreso.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PagPrinLoggin.add(BotonIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 110, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PagPrinLoggin, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PagPrinLoggin, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonIngreso;
    private javax.swing.JTextField CContrasena;
    private javax.swing.JTextField CamUsuario;
    private javax.swing.JLabel Contrasena;
    private javax.swing.JLabel ImagenUsuario;
    private javax.swing.JLabel OlvidoContrasena;
    private javax.swing.JPanel PagPrinLoggin;
    private javax.swing.JLabel Usuario;
    // End of variables declaration//GEN-END:variables
}
