/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProyFundacionNH.view;

/**
 *
 * @author USUARIO
 */
public class Notificaciones extends javax.swing.JFrame {

    /**
     * Creates new form Notificaciones
     */
    public Notificaciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ImagenFundación = new javax.swing.JLabel();
        Notificaciones = new javax.swing.JLabel();
        PanelMorado = new javax.swing.JTextField();
        ImagenCruz = new javax.swing.JLabel();
        GenerarAlerta = new javax.swing.JTextField();
        ImagenCampana = new javax.swing.JLabel();
        AlertaAsistencia = new javax.swing.JTextField();
        EstudianteAler = new javax.swing.JTextField();
        InasistenciaClaseDe = new javax.swing.JTextField();
        PanelAsistencia = new javax.swing.JPanel();
        Hace5min = new javax.swing.JTextField();
        ImagenCampanaPsico = new javax.swing.JLabel();
        AlertaAsistenciaPsico = new javax.swing.JTextField();
        EstudianteAlerPsico = new javax.swing.JTextField();
        InasistenciaPsico = new javax.swing.JTextField();
        PanelPsico = new javax.swing.JPanel();
        Hace5minPsico = new javax.swing.JTextField();
        ImagenCampanaAsis2 = new javax.swing.JLabel();
        AlertaAsistencia2 = new javax.swing.JTextField();
        EstudianteAsistencia2 = new javax.swing.JTextField();
        AlerInasistencia2 = new javax.swing.JTextField();
        PanelPsico1 = new javax.swing.JPanel();
        Hace5minAlerInas2 = new javax.swing.JTextField();
        AsistenciaAlert = new javax.swing.JComboBox<>();
        GeneradaPor = new javax.swing.JLabel();
        AsistenciaAler1 = new javax.swing.JComboBox<>();
        Observacion = new javax.swing.JLabel();
        EstudianteAlerta = new javax.swing.JComboBox<>();
        AlertEstudian1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        TipoDeAlerta = new javax.swing.JLabel();
        Alerta = new javax.swing.JLabel();
        GeneradaPor1 = new javax.swing.JLabel();
        AsistenciaAlert3 = new javax.swing.JComboBox<>();
        Observacion1 = new javax.swing.JLabel();
        AsistenciaAlert2 = new javax.swing.JComboBox<>();
        EstudianteAlerta1 = new javax.swing.JComboBox<>();
        AlertEstudian2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        Alerta1 = new javax.swing.JLabel();
        TipoDeAlerta1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ImagenFundación.setBackground(new java.awt.Color(224, 0, 204));
        ImagenFundación.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo fundacion2.png"))); // NOI18N
        jPanel1.add(ImagenFundación, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 350, 150));

        Notificaciones.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        Notificaciones.setForeground(new java.awt.Color(204, 0, 204));
        Notificaciones.setText("Notificaciones");
        jPanel1.add(Notificaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 180, 30));

        PanelMorado.setBackground(new java.awt.Color(255, 153, 255));
        PanelMorado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(PanelMorado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 490, -1));

        ImagenCruz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen1.png"))); // NOI18N
        jPanel1.add(ImagenCruz, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, 70));

        GenerarAlerta.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        GenerarAlerta.setText("Generar Alerta");
        jPanel1.add(GenerarAlerta, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 120, -1));

        ImagenCampana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/campana-de-notificacion.png"))); // NOI18N
        jPanel1.add(ImagenCampana, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 40, 40));

        AlertaAsistencia.setText("Alerta - Asistencia");
        jPanel1.add(AlertaAsistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        EstudianteAler.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        EstudianteAler.setText("Estudiante XXXXX");
        EstudianteAler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstudianteAlerActionPerformed(evt);
            }
        });
        jPanel1.add(EstudianteAler, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 160, -1));

        InasistenciaClaseDe.setText("Inasistencia a clase de XXXXX");
        jPanel1.add(InasistenciaClaseDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 210, -1));

        PanelAsistencia.setBorder(new javax.swing.border.MatteBorder(null));

        Hace5min.setText("Hace 5 min");

        javax.swing.GroupLayout PanelAsistenciaLayout = new javax.swing.GroupLayout(PanelAsistencia);
        PanelAsistencia.setLayout(PanelAsistenciaLayout);
        PanelAsistenciaLayout.setHorizontalGroup(
            PanelAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAsistenciaLayout.createSequentialGroup()
                .addContainerGap(328, Short.MAX_VALUE)
                .addComponent(Hace5min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        PanelAsistenciaLayout.setVerticalGroup(
            PanelAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAsistenciaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(Hace5min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jPanel1.add(PanelAsistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 420, 130));

        ImagenCampanaPsico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/campana-de-notificacion.png"))); // NOI18N
        jPanel1.add(ImagenCampanaPsico, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 40, 40));

        AlertaAsistenciaPsico.setText("Alerta - Psicologìa");
        jPanel1.add(AlertaAsistenciaPsico, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, -1, -1));

        EstudianteAlerPsico.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        EstudianteAlerPsico.setText("Estudiante XXXXX");
        EstudianteAlerPsico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstudianteAlerPsicoActionPerformed(evt);
            }
        });
        jPanel1.add(EstudianteAlerPsico, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 160, -1));

        InasistenciaPsico.setText("Inicio de sesión");
        jPanel1.add(InasistenciaPsico, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 210, -1));

        PanelPsico.setBorder(new javax.swing.border.MatteBorder(null));

        Hace5minPsico.setText("Hace 5 min");

        javax.swing.GroupLayout PanelPsicoLayout = new javax.swing.GroupLayout(PanelPsico);
        PanelPsico.setLayout(PanelPsicoLayout);
        PanelPsicoLayout.setHorizontalGroup(
            PanelPsicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPsicoLayout.createSequentialGroup()
                .addContainerGap(328, Short.MAX_VALUE)
                .addComponent(Hace5minPsico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        PanelPsicoLayout.setVerticalGroup(
            PanelPsicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPsicoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(Hace5minPsico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jPanel1.add(PanelPsico, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 420, 130));

        ImagenCampanaAsis2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/campana-de-notificacion.png"))); // NOI18N
        jPanel1.add(ImagenCampanaAsis2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, 40, 40));

        AlertaAsistencia2.setText("Alerta - Asistencia 2");
        jPanel1.add(AlertaAsistencia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 570, -1, -1));

        EstudianteAsistencia2.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        EstudianteAsistencia2.setText("Estudiante XXXXX");
        EstudianteAsistencia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstudianteAsistencia2ActionPerformed(evt);
            }
        });
        jPanel1.add(EstudianteAsistencia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 610, 160, -1));

        AlerInasistencia2.setText("Inicio de sesión");
        jPanel1.add(AlerInasistencia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 640, 210, -1));

        PanelPsico1.setBorder(new javax.swing.border.MatteBorder(null));

        Hace5minAlerInas2.setText("Hace 5 min");

        javax.swing.GroupLayout PanelPsico1Layout = new javax.swing.GroupLayout(PanelPsico1);
        PanelPsico1.setLayout(PanelPsico1Layout);
        PanelPsico1Layout.setHorizontalGroup(
            PanelPsico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPsico1Layout.createSequentialGroup()
                .addContainerGap(328, Short.MAX_VALUE)
                .addComponent(Hace5minAlerInas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        PanelPsico1Layout.setVerticalGroup(
            PanelPsico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPsico1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(Hace5minAlerInas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jPanel1.add(PanelPsico1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 420, 130));

        AsistenciaAlert.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Asistencia" }));
        jPanel1.add(AsistenciaAlert, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 740, 190, -1));

        GeneradaPor.setText("Generada Por:");
        jPanel1.add(GeneradaPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 770, -1, -1));

        AsistenciaAler1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Profesor XXXX" }));
        jPanel1.add(AsistenciaAler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 770, 190, -1));

        Observacion.setText("Observaciones");
        jPanel1.add(Observacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 840, -1, -1));

        EstudianteAlerta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "XXXXXXXXXXXXXXXXXXXXX" }));
        jPanel1.add(EstudianteAlerta, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 800, 290, -1));

        AlertEstudian1.setText("Estudiante");
        jPanel1.add(AlertEstudian1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 800, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Inasistencia a la clase de danzas\n");
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 860, 380, -1));

        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));

        TipoDeAlerta.setText("Tipo de Alerta:");

        Alerta.setText("Alerta");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Alerta)
                    .addComponent(TipoDeAlerta))
                .addContainerGap(322, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Alerta)
                .addGap(21, 21, 21)
                .addComponent(TipoDeAlerta)
                .addContainerGap(199, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 700, 420, 260));

        GeneradaPor1.setText("Generada Por:");
        jPanel1.add(GeneradaPor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1040, -1, -1));

        AsistenciaAlert3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Asistencia" }));
        jPanel1.add(AsistenciaAlert3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 1010, 190, -1));

        Observacion1.setText("Observaciones");
        jPanel1.add(Observacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1110, -1, -1));

        AsistenciaAlert2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Profesor XXXX" }));
        jPanel1.add(AsistenciaAlert2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 1040, 190, -1));

        EstudianteAlerta1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "XXXXXXXXXXXXXXXXXXXXX" }));
        jPanel1.add(EstudianteAlerta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 1070, 290, -1));

        AlertEstudian2.setText("Estudiante");
        jPanel1.add(AlertEstudian2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1070, -1, -1));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("Ingrese un comentario adicional\n\n");
        jScrollPane2.setViewportView(jTextArea2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1130, 380, -1));

        Alerta1.setText("Alerta");
        jPanel1.add(Alerta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 980, -1, -1));

        TipoDeAlerta1.setText("Tipo de Alerta:");
        jPanel1.add(TipoDeAlerta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 1020, -1, -1));

        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 258, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 970, 420, 260));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1253, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EstudianteAlerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstudianteAlerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EstudianteAlerActionPerformed

    private void EstudianteAlerPsicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstudianteAlerPsicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EstudianteAlerPsicoActionPerformed

    private void EstudianteAsistencia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstudianteAsistencia2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EstudianteAsistencia2ActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AlerInasistencia2;
    private javax.swing.JLabel AlertEstudian1;
    private javax.swing.JLabel AlertEstudian2;
    private javax.swing.JLabel Alerta;
    private javax.swing.JLabel Alerta1;
    private javax.swing.JTextField AlertaAsistencia;
    private javax.swing.JTextField AlertaAsistencia2;
    private javax.swing.JTextField AlertaAsistenciaPsico;
    private javax.swing.JComboBox<String> AsistenciaAler1;
    private javax.swing.JComboBox<String> AsistenciaAlert;
    private javax.swing.JComboBox<String> AsistenciaAlert2;
    private javax.swing.JComboBox<String> AsistenciaAlert3;
    private javax.swing.JTextField EstudianteAler;
    private javax.swing.JTextField EstudianteAlerPsico;
    private javax.swing.JComboBox<String> EstudianteAlerta;
    private javax.swing.JComboBox<String> EstudianteAlerta1;
    private javax.swing.JTextField EstudianteAsistencia2;
    private javax.swing.JLabel GeneradaPor;
    private javax.swing.JLabel GeneradaPor1;
    private javax.swing.JTextField GenerarAlerta;
    private javax.swing.JTextField Hace5min;
    private javax.swing.JTextField Hace5minAlerInas2;
    private javax.swing.JTextField Hace5minPsico;
    private javax.swing.JLabel ImagenCampana;
    private javax.swing.JLabel ImagenCampanaAsis2;
    private javax.swing.JLabel ImagenCampanaPsico;
    private javax.swing.JLabel ImagenCruz;
    private javax.swing.JLabel ImagenFundación;
    private javax.swing.JTextField InasistenciaClaseDe;
    private javax.swing.JTextField InasistenciaPsico;
    private javax.swing.JLabel Notificaciones;
    private javax.swing.JLabel Observacion;
    private javax.swing.JLabel Observacion1;
    private javax.swing.JPanel PanelAsistencia;
    private javax.swing.JTextField PanelMorado;
    private javax.swing.JPanel PanelPsico;
    private javax.swing.JPanel PanelPsico1;
    private javax.swing.JLabel TipoDeAlerta;
    private javax.swing.JLabel TipoDeAlerta1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
