/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProyFundacionNH.view;

/**
 *
 * @author USUARIO
 */
public class perfil_estudiante extends javax.swing.JFrame {

    /**
     * Creates new form perfil_estudiante
     */
    public perfil_estudiante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Imagenestud = new javax.swing.JLabel();
        NomFunda = new javax.swing.JLabel();
        NombreEst = new javax.swing.JLabel();
        CNombreEst = new javax.swing.JTextField();
        ApelliEst1 = new javax.swing.JLabel();
        CApelliEst1 = new javax.swing.JTextField();
        CodigoEst = new javax.swing.JLabel();
        CCodiest = new javax.swing.JTextField();
        DatGene = new javax.swing.JLabel();
        DocumenEst = new javax.swing.JLabel();
        CdocumEst = new javax.swing.JComboBox<>();
        FechaNacEst = new javax.swing.JLabel();
        CFecNacEst = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        NumeroEst = new javax.swing.JLabel();
        CNumEst = new javax.swing.JTextField();
        Ciudad = new javax.swing.JLabel();
        CCiudad = new javax.swing.JTextField();
        DatMed = new javax.swing.JLabel();
        Sisben = new javax.swing.JLabel();
        CSisben = new javax.swing.JTextField();
        Eps = new javax.swing.JLabel();
        CEps = new javax.swing.JTextField();
        TipoSangre = new javax.swing.JLabel();
        Discapacidad = new javax.swing.JLabel();
        CTipoSangre = new javax.swing.JTextField();
        CdocumEst1 = new javax.swing.JComboBox<>();
        NonbreIncap = new javax.swing.JLabel();
        CNomInca = new javax.swing.JLabel();
        AlerMedic = new javax.swing.JLabel();
        CAlerMedi = new javax.swing.JComboBox<>();
        CAlergMed = new javax.swing.JLabel();
        CAlerAlim = new javax.swing.JLabel();
        AlerAlim = new javax.swing.JLabel();
        CAlergAlim = new javax.swing.JComboBox<>();
        AlerAlim1 = new javax.swing.JLabel();
        CAlergAlim1 = new javax.swing.JComboBox<>();
        CAlerAlim1 = new javax.swing.JLabel();
        DatAcudi = new javax.swing.JLabel();
        NombresAcud = new javax.swing.JLabel();
        CNomAcud = new javax.swing.JTextField();
        Apellidos = new javax.swing.JLabel();
        CNomAcud1 = new javax.swing.JTextField();
        DirecciónAcud = new javax.swing.JLabel();
        CDireccAcud = new javax.swing.JTextField();
        BarrioAcud = new javax.swing.JLabel();
        CBarrioAcud = new javax.swing.JTextField();
        CalularAcud = new javax.swing.JLabel();
        CCelularAcud = new javax.swing.JTextField();
        FijoAcud = new javax.swing.JLabel();
        CFijoAcud = new javax.swing.JTextField();
        DatAcademicos = new javax.swing.JLabel();
        Teatro = new javax.swing.JLabel();
        CTeatro = new javax.swing.JTextField();
        Danzas = new javax.swing.JLabel();
        CDanzas = new javax.swing.JTextField();
        Musica = new javax.swing.JLabel();
        CMusica = new javax.swing.JTextField();
        EducComplemen = new javax.swing.JLabel();
        CEducCompleme = new javax.swing.JTextField();
        EducAlmas = new javax.swing.JLabel();
        CEducAlmas = new javax.swing.JTextField();
        AlimentoConAmor = new javax.swing.JLabel();
        CAlimenConAmor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Imagenestud.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(Imagenestud, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 170, 190));

        NomFunda.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        NomFunda.setForeground(new java.awt.Color(204, 0, 204));
        NomFunda.setText("Fundación Nuestro Hogar");
        jPanel1.add(NomFunda, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 220, 20));

        NombreEst.setText("Nombre:");
        jPanel1.add(NombreEst, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, -1, -1));
        jPanel1.add(CNombreEst, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 220, -1));

        ApelliEst1.setText("Apellidos:");
        jPanel1.add(ApelliEst1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, -1));
        jPanel1.add(CApelliEst1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 220, -1));

        CodigoEst.setText("Código:");
        jPanel1.add(CodigoEst, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, -1, -1));
        jPanel1.add(CCodiest, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 220, -1));

        DatGene.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        DatGene.setForeground(new java.awt.Color(204, 0, 204));
        DatGene.setText("Datos Generales");
        jPanel1.add(DatGene, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 140, 20));

        DocumenEst.setText("Documento:");
        jPanel1.add(DocumenEst, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 80, -1));

        CdocumEst.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo" }));
        jPanel1.add(CdocumEst, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 140, -1));

        FechaNacEst.setText("Fecha Nacimiento:");
        jPanel1.add(FechaNacEst, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 110, -1));

        CFecNacEst.setText("      /       /");
        jPanel1.add(CFecNacEst, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 80, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calendar_day_month_date_year_schedule_icon_175594.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 50, 40));

        NumeroEst.setText("Número:");
        jPanel1.add(NumeroEst, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, -1, -1));
        jPanel1.add(CNumEst, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 130, -1));

        Ciudad.setText("Ciudad:");
        jPanel1.add(Ciudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, -1, -1));
        jPanel1.add(CCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 130, -1));

        DatMed.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        DatMed.setForeground(new java.awt.Color(204, 0, 204));
        DatMed.setText("Datos Médicos");
        jPanel1.add(DatMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 140, 20));

        Sisben.setText("Sisben:");
        jPanel1.add(Sisben, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));
        jPanel1.add(CSisben, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 130, -1));

        Eps.setText("Eps:");
        jPanel1.add(Eps, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 450, -1, -1));
        jPanel1.add(CEps, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 450, 130, -1));

        TipoSangre.setText("Tipo de Sangre:");
        jPanel1.add(TipoSangre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 100, -1));

        Discapacidad.setText("Discapacidad :");
        jPanel1.add(Discapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 490, 80, -1));
        jPanel1.add(CTipoSangre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, 130, -1));

        CdocumEst1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo" }));
        jPanel1.add(CdocumEst1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 490, 140, -1));

        NonbreIncap.setText("Nombre la incapacidad:");
        jPanel1.add(NonbreIncap, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, -1));

        CNomInca.setText("Describa cual o cuales");
        CNomInca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(CNomInca, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 470, 40));

        AlerMedic.setText("Alergico a algún medicamento:");
        jPanel1.add(AlerMedic, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, 170, -1));

        CAlerMedi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opciòn" }));
        jPanel1.add(CAlerMedi, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 610, 230, -1));

        CAlergMed.setText("Describa cual o cuales");
        CAlergMed.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(CAlergMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 640, 470, 40));

        CAlerAlim.setText("Describa cual o cuales");
        CAlerAlim.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(CAlerAlim, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 730, 470, 40));

        AlerAlim.setText("Alergico a algún alimento:");
        jPanel1.add(AlerAlim, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 700, 170, -1));

        CAlergAlim.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opciòn" }));
        jPanel1.add(CAlergAlim, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 700, 230, -1));

        AlerAlim1.setText("Toma algún medicameno:");
        jPanel1.add(AlerAlim1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 790, 170, -1));

        CAlergAlim1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opciòn" }));
        jPanel1.add(CAlergAlim1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 790, 230, -1));

        CAlerAlim1.setText("Describa cual o cuales");
        CAlerAlim1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(CAlerAlim1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 820, 470, 40));

        DatAcudi.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        DatAcudi.setForeground(new java.awt.Color(204, 0, 204));
        DatAcudi.setText("Datos Acudiente");
        jPanel1.add(DatAcudi, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 890, 140, 20));

        NombresAcud.setText("Nombres:");
        jPanel1.add(NombresAcud, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 930, -1, -1));
        jPanel1.add(CNomAcud, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 930, 160, -1));

        Apellidos.setText("Apellidos:");
        jPanel1.add(Apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 930, -1, -1));
        jPanel1.add(CNomAcud1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 930, 190, -1));

        DirecciónAcud.setText("Dirección:");
        jPanel1.add(DirecciónAcud, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 960, -1, -1));
        jPanel1.add(CDireccAcud, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 960, 160, -1));

        BarrioAcud.setText("Barrio:");
        jPanel1.add(BarrioAcud, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 960, -1, -1));
        jPanel1.add(CBarrioAcud, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 960, 190, -1));

        CalularAcud.setText("Celular:");
        jPanel1.add(CalularAcud, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 990, -1, -1));
        jPanel1.add(CCelularAcud, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 990, 160, -1));

        FijoAcud.setText("Fijo:");
        jPanel1.add(FijoAcud, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 990, -1, -1));
        jPanel1.add(CFijoAcud, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 990, 190, -1));

        DatAcademicos.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        DatAcademicos.setForeground(new java.awt.Color(204, 0, 204));
        DatAcademicos.setText("Datos Académicos");
        jPanel1.add(DatAcademicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 1040, 170, 20));

        Teatro.setText("Teatro:");
        jPanel1.add(Teatro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1070, -1, -1));

        CTeatro.setText("Observaciones....");
        jPanel1.add(CTeatro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1090, 480, 30));

        Danzas.setText("Danzas:");
        jPanel1.add(Danzas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1130, -1, -1));

        CDanzas.setText("Observaciones....");
        jPanel1.add(CDanzas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1150, 480, 30));

        Musica.setText("Música :");
        jPanel1.add(Musica, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1190, -1, -1));

        CMusica.setText("Observaciones....");
        jPanel1.add(CMusica, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1210, 480, 30));

        EducComplemen.setText("Educación Complementaria:");
        jPanel1.add(EducComplemen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1250, -1, -1));

        CEducCompleme.setText("Observaciones....");
        jPanel1.add(CEducCompleme, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1270, 480, 30));

        EducAlmas.setText("Educando Almas:");
        jPanel1.add(EducAlmas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1310, -1, -1));

        CEducAlmas.setText("Observaciones....");
        jPanel1.add(CEducAlmas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1330, 480, 30));

        AlimentoConAmor.setText("Alimento con amor:");
        jPanel1.add(AlimentoConAmor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1370, -1, -1));

        CAlimenConAmor.setText("Observaciones....");
        jPanel1.add(CAlimenConAmor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1390, 480, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlerAlim;
    private javax.swing.JLabel AlerAlim1;
    private javax.swing.JLabel AlerMedic;
    private javax.swing.JLabel AlimentoConAmor;
    private javax.swing.JLabel ApelliEst1;
    private javax.swing.JLabel Apellidos;
    private javax.swing.JLabel BarrioAcud;
    private javax.swing.JLabel CAlerAlim;
    private javax.swing.JLabel CAlerAlim1;
    private javax.swing.JComboBox<String> CAlerMedi;
    private javax.swing.JComboBox<String> CAlergAlim;
    private javax.swing.JComboBox<String> CAlergAlim1;
    private javax.swing.JLabel CAlergMed;
    private javax.swing.JTextField CAlimenConAmor;
    private javax.swing.JTextField CApelliEst1;
    private javax.swing.JTextField CBarrioAcud;
    private javax.swing.JTextField CCelularAcud;
    private javax.swing.JTextField CCiudad;
    private javax.swing.JTextField CCodiest;
    private javax.swing.JTextField CDanzas;
    private javax.swing.JTextField CDireccAcud;
    private javax.swing.JTextField CEducAlmas;
    private javax.swing.JTextField CEducCompleme;
    private javax.swing.JTextField CEps;
    private javax.swing.JFormattedTextField CFecNacEst;
    private javax.swing.JTextField CFijoAcud;
    private javax.swing.JTextField CMusica;
    private javax.swing.JTextField CNomAcud;
    private javax.swing.JTextField CNomAcud1;
    private javax.swing.JLabel CNomInca;
    private javax.swing.JTextField CNombreEst;
    private javax.swing.JTextField CNumEst;
    private javax.swing.JTextField CSisben;
    private javax.swing.JTextField CTeatro;
    private javax.swing.JTextField CTipoSangre;
    private javax.swing.JLabel CalularAcud;
    private javax.swing.JComboBox<String> CdocumEst;
    private javax.swing.JComboBox<String> CdocumEst1;
    private javax.swing.JLabel Ciudad;
    private javax.swing.JLabel CodigoEst;
    private javax.swing.JLabel Danzas;
    private javax.swing.JLabel DatAcademicos;
    private javax.swing.JLabel DatAcudi;
    private javax.swing.JLabel DatGene;
    private javax.swing.JLabel DatMed;
    private javax.swing.JLabel DirecciónAcud;
    private javax.swing.JLabel Discapacidad;
    private javax.swing.JLabel DocumenEst;
    private javax.swing.JLabel EducAlmas;
    private javax.swing.JLabel EducComplemen;
    private javax.swing.JLabel Eps;
    private javax.swing.JLabel FechaNacEst;
    private javax.swing.JLabel FijoAcud;
    private javax.swing.JLabel Imagenestud;
    private javax.swing.JLabel Musica;
    private javax.swing.JLabel NomFunda;
    private javax.swing.JLabel NombreEst;
    private javax.swing.JLabel NombresAcud;
    private javax.swing.JLabel NonbreIncap;
    private javax.swing.JLabel NumeroEst;
    private javax.swing.JLabel Sisben;
    private javax.swing.JLabel Teatro;
    private javax.swing.JLabel TipoSangre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
