/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProyFundacionNH.view;

/**
 *
 * @author USUARIO
 */
public class Psicología extends javax.swing.JFrame {

    /**
     * Creates new form Psicología
     */
    public Psicología() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ImagenLogoFund = new javax.swing.JLabel();
        Psicología = new javax.swing.JLabel();
        NombrePsicologo = new javax.swing.JLabel();
        CampoNomPsico = new javax.swing.JComboBox<>();
        NombreEstu = new javax.swing.JLabel();
        Estudiantes = new javax.swing.JScrollPane();
        ListaEstudiantes = new javax.swing.JList<>();
        Alerta = new javax.swing.JLabel();
        CampoAlerta = new javax.swing.JComboBox<>();
        CampoPrimSec = new java.awt.TextArea();
        CampoPrimSes = new javax.swing.JLabel();
        SegundaSesion = new javax.swing.JLabel();
        CampoSegSes = new java.awt.TextArea();
        CampoTercSes = new javax.swing.JLabel();
        CampoTercSec = new java.awt.TextArea();
        CampoObser = new javax.swing.JLabel();
        CampoObse = new java.awt.TextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ImagenLogoFund.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo fundacion2.png"))); // NOI18N
        jPanel1.add(ImagenLogoFund, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 320, 80));

        Psicología.setBackground(new java.awt.Color(240, 0, 240));
        Psicología.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Psicología.setForeground(new java.awt.Color(240, 0, 240));
        Psicología.setText("PSICOLOGÍA");
        jPanel1.add(Psicología, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 120, -1));

        NombrePsicologo.setText("Nombre Psicologo");
        jPanel1.add(NombrePsicologo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 126, -1, 30));

        CampoNomPsico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el Psicologo" }));
        jPanel1.add(CampoNomPsico, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 190, -1));

        NombreEstu.setText("Nombre Estudiante");
        jPanel1.add(NombreEstu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        Estudiantes.setViewportView(ListaEstudiantes);

        jPanel1.add(Estudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, 30));

        Alerta.setText("Alerta creada por:");
        jPanel1.add(Alerta, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, -1, -1));

        jPanel1.add(CampoAlerta, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 200, -1));
        jPanel1.add(CampoPrimSec, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 540, 160));

        CampoPrimSes.setText("Primera sesión:");
        jPanel1.add(CampoPrimSes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        SegundaSesion.setText("Segunda sesión");
        jPanel1.add(SegundaSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));
        jPanel1.add(CampoSegSes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 540, 160));

        CampoTercSes.setText("Tercera sesión");
        jPanel1.add(CampoTercSes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 630, -1, -1));
        jPanel1.add(CampoTercSec, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 650, 540, 180));

        CampoObser.setText("Observaciones:");
        jPanel1.add(CampoObser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 840, -1, -1));
        jPanel1.add(CampoObse, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 860, 540, 160));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1029, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alerta;
    private javax.swing.JComboBox<String> CampoAlerta;
    private javax.swing.JComboBox<String> CampoNomPsico;
    private java.awt.TextArea CampoObse;
    private javax.swing.JLabel CampoObser;
    private java.awt.TextArea CampoPrimSec;
    private javax.swing.JLabel CampoPrimSes;
    private java.awt.TextArea CampoSegSes;
    private java.awt.TextArea CampoTercSec;
    private javax.swing.JLabel CampoTercSes;
    private javax.swing.JScrollPane Estudiantes;
    private javax.swing.JLabel ImagenLogoFund;
    private javax.swing.JList<String> ListaEstudiantes;
    private javax.swing.JLabel NombreEstu;
    private javax.swing.JLabel NombrePsicologo;
    private javax.swing.JLabel Psicología;
    private javax.swing.JLabel SegundaSesion;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
