/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProyFundacionNH.view;

/**
 *
 * @author USUARIO
 */
public class Recuperar_Contraseña extends javax.swing.JFrame {

    /**
     * Creates new form Recuperar_Contraseña
     */
    public Recuperar_Contraseña() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Usuario = new javax.swing.JLabel();
        Cusuario = new javax.swing.JTextField();
        ContraseñaNueva = new javax.swing.JLabel();
        CContraNueva = new javax.swing.JTextField();
        ConfContras = new javax.swing.JLabel();
        CConfirContra = new javax.swing.JTextField();
        EnvioSolici = new javax.swing.JButton();
        ImagenCandado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Usuario.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        Usuario.setText("Usuario:");
        jPanel1.add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));
        jPanel1.add(Cusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 280, -1));

        ContraseñaNueva.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        ContraseñaNueva.setText("Contraseña nueva:");
        jPanel1.add(ContraseñaNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));
        jPanel1.add(CContraNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 280, -1));

        ConfContras.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        ConfContras.setText("Confirmar contraseña:");
        jPanel1.add(ConfContras, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 220, -1));
        jPanel1.add(CConfirContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 280, -1));

        EnvioSolici.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        EnvioSolici.setText("Enviar Solicitud");
        EnvioSolici.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(EnvioSolici, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 160, 50));

        ImagenCandado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cambio contraseña.png"))); // NOI18N
        ImagenCandado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(ImagenCandado, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 80, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CConfirContra;
    private javax.swing.JTextField CContraNueva;
    private javax.swing.JLabel ConfContras;
    private javax.swing.JLabel ContraseñaNueva;
    private javax.swing.JTextField Cusuario;
    private javax.swing.JButton EnvioSolici;
    private javax.swing.JLabel ImagenCandado;
    private javax.swing.JLabel Usuario;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
